### create a presigned upload URL
POST localhost:8080/v3/upload
Content-Type: application/json
Authorization: Basic admin admin

{
    "id": "6e9e34e8-b8ec-4c11-9b23-16dd951bb480",
    "download": {
        "name": "test.txt",
        "checksums": {
            "sha256": "66a045b452102c59d840ec097d59d9467e13a3f34f6494e539ffd32c1bb35f18"
        },
        "size": 6
    },
    "contentMd5": "CffgLxKQviEdpweiZvFTsw=="
}

> {% client.global.set("uploadUrl", response.body.url); %}

### upload the payload
PUT {{uploadUrl}}
Content-Length: 6
Content-MD5: CffgLxKQviEdpweiZvFTsw==
Content-Type: application/java-archive
x-amz-meta-sha256: 66a045b452102c59d840ec097d59d9467e13a3f34f6494e539ffd32c1bb35f18

< test.txt

### publish a build
POST localhost:8080/v3/publish
Content-Type: application/json
Authorization: Basic admin admin

{
    "id": "6e9e34e8-b8ec-4c11-9b23-16dd951bb480",
    "project": "test-project",
    "family": "1.0",
    "version": "1.0.0",
    "build": "2",
    "time": "{{ $isoTimestamp }}",
    "channel": "STABLE",
    "commits": [{
        "sha": "",
        "time": "{{ $isoTimestamp }}",
        "message": "Initial commit"
    }],
    "downloads": {
        "server:default": {
            "name": "test.txt",
            "checksums": {
              "sha256": "66a045b452102c59d840ec097d59d9467e13a3f34f6494e539ffd32c1bb35f18"
            },
            "size": 6
        }
    }
}


### get projects
GET localhost:8080/v3/projects

### get versions
GET localhost:8080/v3/projects/test-project/versions

### get builds
GET localhost:8080/v3/projects/test-project/versions/1.0.0/builds

### get build
GET localhost:8080/v3/projects/test-project/versions/1.0.0/builds/1

### get latest build
GET localhost:8080/v3/projects/test-project/versions/1.0.0/builds/latest
