management:
  endpoint:
    health:
      access: read_only
  endpoints:
    access:
      default: read_only

server:
  error:
    whitelabel:
      enabled: false

spring:
  data:
    mongodb:
      auto-index-creation: true
      database: fill
  graphql:
    cors:
      allowed-origin-patterns: *
    graphiql:
      enabled: true
    schema:
      printer:
        enabled: true
  servlet:
    multipart:
      max-file-size: 55MB
      max-request-size: 70MB
  web:
    resources:
      add-mappings: false

springdoc:
  api-docs:
    path: /openapi.yaml
  swagger-ui:
    path: /
  writer-with-order-by-keys: true
