management:
  endpoint:
    health:
      access: read_only
  endpoints:
    access:
      default: read_only

spring:
  data:
    mongodb:
      auto-index-creation: true
  graphql:
    cors:
      allowed-origin-patterns: "*"
    graphiql:
      enabled: true
    schema:
      printer:
        enabled: true
  mongodb:
    database: fill
  servlet:
    multipart:
      max-file-size: 75MB
      max-request-size: 100MB
  web:
    error:
      whitelabel:
        enabled: false
    resources:
      add-mappings: false

springdoc:
  api-docs:
    path: /openapi.yaml
  swagger-ui:
    path: /
  writer-with-order-by-keys: true
