# This GraphQL query retrieves information about the paper project, specifically focusing on its currently supported versions. For each supported version, it fetches:
# - The version id
# - The minimum required Java version and any recommended Java flags
# - The most recent build (last: 1) including:
#   - build id
#   - The server:default download artifact, including:
#     - file name
#     - sha-256 checksum
#     - file size (in bytes)
#     - direct download url
query {
  project(key: "paper") {
    id
    key
    versions(filterBy: {supportStatus: SUPPORTED}, orderBy: {direction: DESC}, first: 1) {
      edges {
        node {
          id
          key
          support {
            status
            end
          }
          java {
            version {
              minimum
            }
            flags {
              recommended
            }
          }
          builds(orderBy: {direction: DESC}, first: 1) {
            edges {
              node {
                id
                number
                createdAt
                channel
                download(key: "server:default") {
                  name
                  checksums {
                    sha256
                  }
                  size
                  url
                }
              }
            }
          }
        }
      }
    }
  }
}
