name: publish

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: namespace-profile-linux-default
    timeout-minutes: 30
    steps:
      - name: "git / checkout"
        uses: namespacelabs/nscloud-checkout-action@66f2dc6f6c42a8ac6c4e53473c4840006822831e # v9.0.1

      - name: "docker / login"
        uses: docker/login-action@dbcb813823bdd20940b903addbd779551569679f # v4.6.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: "java / setup"
        uses: actions/setup-java@b6effb05e454b25005698d916606bdc6ffcbf961 # v5.7.0
        with:
          check-latest: true
          distribution: zulu
          java-version: 25
          cache: "" # namespace handles this

      - name: "gradle / cache"
        uses: namespacelabs/nscloud-cache-action@1124a6f3ce44e5cf84cc22111530961f4d2a15f9 # v1.7.0
        with:
          cache: gradle

      - name: "gradle / build cache"
        run: |
          nsc cache gradle setup --init-gradle /tmp/init.gradle

      - name: "gradle / setup"
        uses: gradle/actions/setup-gradle@9c971963bec38e04b3d30dcc455b5382be2fdbfb # v6.3.0
        with:
          cache-disabled: true # namespace handles this

      - name: "gradle / build"
        run: ./gradlew --init-script=/tmp/init.gradle jib -Djib.console=plain --stacktrace
